name: food_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  country_flags: ^2.2.0
  flutter:
    sdk: flutter
  page_transition: ^2.1.0
  qr_code_scanner: ^1.0.1
  simple_animations: ^5.0.2
  collection: ^1.17.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_lints: ^2.0.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  google_maps_flutter: ^2.2.3
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/
   - assets/images/starter-image.jpg
   - assets/images/one.jpg
   - assets/images/two.jpg
   - assets/images/three.jpg
   - assets/images/catamaran.png

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200